[WIP] Gradle: Integrate JaCoCo test reporter
Gradle plugin: https://docs.gradle.org/current/userguide/jacoco_plugin.html.

Based on https://github.com/thsaravana/jacoco-playground as it apparently is very hard find a working guide for integrating this tool into a Kotlin/Android project (this one didn't completely work but might include useful stuff, who knows: https://veskoiliev.com/how-to-setup-jacoco-for-android-project-with-java-kotlin-and-multiple-flavours/).

Intending to use https://github.com/marketplace/actions/jacoco-report for publishing the results into PRs.

Included an "exclude" for addressing some exception (https://stackoverflow.com/questions/68065743/cannot-run-gradle-test-tasks-because-of-java-lang-noclassdeffounderror-jdk-inte)...